### ISSUE TITLE
September test/fix QC

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Optimized-architecture#17]
WDS presenter presentation (PPT) - slide missing alt-text.
Trainer/Student guides & HOL step-by-step - solution alt-texts need more detailed descriptions

**Comment by zobayer098** [comment]
Hi

I updated the HOL step by step with more detailed alt-texts. Please review and let us know if we can assist anything else.

Thanks
Abu

**Comment by DawnmarieDesJardins** [comment]
Thanks Abu, closing the issue & updating the HTML files.
