### ISSUE TITLE
Getting Started Contents

### ISSUE THREAD

**Issue by lisadown** [Microsoft/MCW-Optimized-architecture#8]
**TEAM ISSUE:**  @Microsoft/microsoft-cloud-workshop

Need to determine how we will manage getting started contents; i.e. all at the uber level or unique to each workshop? e.g. invitation templates (where field has requested these be unique to each workshop)

**Comment by hopero929** [comment]
We will leave it at the uber level. It is too much to manage with unique content per workshop.
